# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.0.0
    steps:
      - checkout
      # CircleCI needs global installs to be sudo
      - run: sudo npm install --global @apollo/rover
      - run: rover graph check metagame@current --schema ./schema.graphql
